version: "3.8" #docker-compose version

services:
    react-app-dockerize:
        # Set the container name
        container_name: react-app-dockerize_c

        # set name for the image
        image: react-app-dockerize_i

        # Build the image using the Dockerfile in the current context
        build:
            context: .
            dockerfile: Dockerfile

            # Map host port 5002 to container port 5002
        ports:
            - "5002:5002" #<host_port>:<container_port/protocol_port>

        # Mount the current directory to /app in the container
        volumes:
            - .:/app
            - /app/node_modules

        # Specify the command to run when the container starts
        command: npm run dev
